/*
MINX_Monsters - A C++ Game Based off the
Copyright (C) 2013  MINX Team

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

*/

//AUTOGENERATED FILE: DO NOT EDIT
#include <Game.h>
#include <Input/Keyboard.h>
#ifndef MONSTERS_H_
#define MONSTERS_H_

using namespace MINX;


namespace MINX_monsters
{
	class MonsterGame : public Game
	{
		public:
			MonsterGame();
			void Initialize();
			void LoadContent();
			void UnloadContent();
			void Update(GameTime * gametime);
			void Draw(GameTime * gametime);
			Input::Keyboard* keyboard;
	};
}

#endif
