#    MINX - A C++ Graphics and Input Wrapper Library
#    Copyright (C) 2013  MINX Team
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
echo "Please type the directory in which you would like to create the new MINX project: "

read projectDir

echo "Please enter the name you would like to use for the source file of your new project (no extension): "

read fileName

Header_define="$(echo $fileName | tr '[:lower:]' '[:upper:]' | tr -d [:space:] | tr -d [:punct:])_H_"

test -d "$projectDir" || mkdir -p "$projectDir";

echo "/*
    MINX - A C++ Graphics and Input Wrapper Library
    Copyright (C) 2013  MINX Team

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

	*/\
//AUTOGENERATED FILE: DO NOT EDIT
#include \"MINX/Game.h\"
#ifndef $Header_define
#define $Header_define

using namespace MINX;

namespace MINX_$fileName
{
	class $fileName : public Game
	{
		public:
			$fileName();
			void Initialize();
			void LoadContent();
			void UnloadContent();
			void Update(GameTime gametime);
			void Draw(GameTime gametime);
	}
}

#endif" > "$projectDir/$fileName.h"

#TODO add stuff for $fileName.cpp, Program.cpp, and makefile
